In [15]:
import numpy as np
a = np.linspace(0,1,24)
b = np.random.rand(4,6)
c = np.sort(b, axis=None).reshape(4,6)
add_arr = np.array([0.69, 0.96, -0.69, 0.22, 0.67, -0.76])
c = c + add_arr
print(c)
c = c.reshape(3,8)
c = c.T
print(c)
mean_value = c.mean()
print(mean_value)
locations = np.where(c > mean_value)
print(locations)



[[ 0.70404861  1.17740528 -0.4698502   0.57395067  1.04363937 -0.32046615]
 [ 1.16184049  1.44379288 -0.18808462  0.72499359  1.17553935 -0.16181078]
 [ 1.29067549  1.56904315 -0.06519002  0.86180276  1.32339871 -0.0886418 ]
 [ 1.47560867  1.80005949  0.24099347  1.16353291  1.64250346  0.23419149]]
[[ 0.70404861 -0.18808462  1.32339871]
 [ 1.17740528  0.72499359 -0.0886418 ]
 [-0.4698502   1.17553935  1.47560867]
 [ 0.57395067 -0.16181078  1.80005949]
 [ 1.04363937  1.29067549  0.24099347]
 [-0.32046615  1.56904315  1.16353291]
 [ 1.16184049 -0.06519002  1.64250346]
 [ 1.44379288  0.86180276  0.23419149]]
0.7630406779429847
(array([0, 1, 2, 2, 3, 4, 4, 5, 5, 6, 6, 7, 7]), array([2, 0, 1, 2, 2, 0, 1, 1, 2, 0, 2, 0, 1]))
